### ISSUE TITLE
Make dropdown menu with searchable country names

### ISSUE THREAD

**Issue by JoryGriffith** [GEO-BON/bon-in-a-box-pipelines#202]
It would be great to have a drop down menu with searchable country names because it is too easy to miswrite.

**Comment by jmlord** [comment]
This is absolutely necessary! Current workaround is to use the markdown feature in the input description to link to the list of acceptable values.

Proposed solution #1:
- Add and document two new custom types: "country" and "region" <-- is region the good snigle-word alternative to "state or province"?
- Support those in the UI
(this is very narrow, works for this case only)

Proposed solution #2:
- Support a link attribute in the options attribute, as such:
```
options_example:
  label: Options example
  description: The user has to select between a fixed number of text options. Also called select or enum. The script receives the selected option as text.
  type: options
  options: http://site.com/api/optionList
  example: third option
  ```
More expandable, but then we'd need to set expectations on the option formats we can read.

@glaroc, thoughts?

**Comment by tpoisot** [comment]
What about using GADM? They have a curated collection of territories and their subdivisions. 

(and using the word "Country" may be debatable as well, not everyone agrees on what a country is...)

**Comment by glaroc** [comment]
The complicated part is the dependent dropdowns. For example, the choice of states/provinces has to depend on the choice of country. For the dependent dropdown, we could have something like 

````
options_country:
  label: Country selector
  description: Choice of countries
  type: options
  options: http://site.com/api/countryList
  example: Colombia
options_province:
  label: State/province selectore
  description: Choice of state/province
  type: options_dependence 
  options: http://site.com/api/provinceList/{options_country}
  example: Putomayo
````
